apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api       # Labels for Deployment Object itself
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api     # Labels which help to find matching pods
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: api   # Labels to be applied to new PODS, Can use More Labels here, later
    spec:
      containers:
        - name: ror
          image: code-challenge-011-api
          imagePullPolicy: Never  # Download from Local Built Images in Minikube or from private registry uploaded image
          ports:
          - containerPort: 3000
          resources: {}
          command: ["/bin/bash"]
          args: ["-c", "rm -f /app/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"] 
          envFrom:
          - configMapRef:
              name: env-cfg
          env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: secrets-vault
                key: postgresdb-password
          volumeMounts:
          - name: minikube-api-mount
            mountPath: /app
      # initContainers:
      restartPolicy: Always     # What can Replication do, if Pod fails
      volumes:
      - name: minikube-api-mount
        hostPath:
          path: /home/docker/api  # Path where I mounted Actual Boilerplate-Code in Minikube(Minikube Hack!)
          type: Directory