apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db      # Labels for Deployment Object itself
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db    # Labels which help to find matching pods
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db  # Labels to be applied to new PODS
    spec:
      containers:
        - name: db
          image: postgres:12.8
          ports:
          - containerPort: 5432
          resources: {}
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-vault
                key: postgresdb-password
          volumeMounts:
            - name: api-db
              mountPath: /var/lib/postgresql/data  # Default Path for PostgreSQL
      restartPolicy: Always
      volumes:
        - name: api-db    
          persistentVolumeClaim:
            claimName: db-pvc       # PVC details are mentioned in separate .YAML file
            
