apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx # Label for Deployment K8 Obj
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx # labels used to find matching PODs
  strategy: {}                  # Deployment Strategy, Default, will make it explicit later
  template:
    metadata:
      labels:
        io.kompose.service: nginx # Labels for POD, Can add more labels later
    spec:
      containers:
        - name: nginx
          image: code-challenge-011-nginx 
          imagePullPolicy: Never # Download from Local Built Images in Minikube or from private registry uploaded image
          ports:
            - containerPort: 8000
          resources: {}          # How much CPU, RAM limit You want to put on this Container 
      restartPolicy: Always      # What to do if Container fails somehow
