apiVersion: v1
kind: Secret
metadata:
  name: secrets-vault
data:
  postgresdb-password: cGFzc3dvcmQK  # Base64 Encoded Value - 'password' literal String

# This is a Declarative way of creating secrets 
#kubectl create secret generic secrets-vault --from-literal='postgresdb-password=password'