apiVersion: v1
kind: Pod    # Init-Container or Job can also be used, Deployment seemed to be overkill
metadata:    # Need to dive deep into Ruby/Rails(Sidekiq)
  name: sidekiq
  labels:
    io.kompose.service: sidekiq
spec:
  containers:
  - name: sidekiq
    image: code-challenge-011-sidekiq
    imagePullPolicy: Never #Trying to fetch it from "minikube image build/load or eval $(minikube docker-env)":
    resources: {}
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    envFrom:
    - configMapRef:
        name: env-cfg
    env:
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: secrets-vault
          key: postgresdb-password
    volumeMounts:
    - name: minikube-mount
      mountPath: /app
  restartPolicy: Always
  volumes:
  - name: minikube-mount
    hostPath:
      path: /home/docker/api # Path where I mounted Actual Boilerplate-Code in Minikube(Minikube Hack!)
      type: Directory