apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spa-npm-pvc           # REDUNDANT!, Not Used, Because node_modules are already Baked in DOCKER Image
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi